development:
  clients:
    default:
      uri: mongodb+srv://dbuser:db123456@cluster0.bryjv.mongodb.net/rentalprofiles?retryWrites=true&w=majority
      options:
        server_selection_timeout: 5
  options:
    raise_not_found_error: false
# test:
#   clients:
#     default:
#       uri: mongodb+srv://dbuser:db123456@cluster0.bryjv.mongodb.net/rentalprofiles?retryWrites=true&w=majority
#       options:
#         server_selection_timeout: 5
#         read:
#           mode: :primary
#         max_pool_size: 1
